### ISSUE TITLE
Start at Login

### ISSUE THREAD

**Issue by albertputinjobs** [CHerSun/NoSleep#1]
Give option to start with login instead of running it manually every time pc boots

**Comment by albertputinjobs** [comment]
chatgpt's response using System;
using System.IO;
using System.Windows.Forms;

namespace YourAppNamespace
{
    public partial class MainForm : Form
    {
        // Your auto-start setting flag
        private bool startOnSignIn = false;

        public MainForm()
        {
            InitializeComponent();
            
            // Load user's auto-start preference from settings
            startOnSignIn = LoadAutoStartPreference();

            // Set checkbox in settings window
            startOnSignInCheckBox.Checked = startOnSignIn;
        }

        private void startOnSignInCheckBox_CheckedChanged(object sender, EventArgs e)
        {
            // Update auto-start preference when user toggles the checkbox
            startOnSignIn = startOnSignInCheckBox.Checked;
            
            // Save auto-start preference to settings
            SaveAutoStartPreference(startOnSignIn);
        }

        private void MainForm_Load(object sender, EventArgs e)
        {
            // Check auto-start setting and add/remove application to/from Startup folder
            if (startOnSignIn)
            {
                AddToStartup();
            }
            else
            {
                RemoveFromStartup();
            }
        }

        private void AddToStartup()
        {
            // Get the path to the user's Startup folder
            string startupFolderPath = Environment.GetFolderPath(Environment.SpecialFolder.Startup);

            // Copy the application executable to the Startup folder
            string appExecutablePath = Application.ExecutablePath;
            string appShortcutPath = Path.Combine(startupFolderPath, "YourAppShortcut.lnk");
            CreateShortcut(appExecutablePath, appShortcutPath);
        }

        private void RemoveFromStartup()
        {
            // Get the path to the user's Startup folder
            string startupFolderPath = Environment.GetFolderPath(Environment.SpecialFolder.Startup);

            // Delete the application shortcut from the Startup folder
            string appShortcutPath = Path.Combine(startupFolderPath, "YourAppShortcut.lnk");
            if (File.Exists(appShortcutPath))
            {
                File.Delete(appShortcutPath);
            }
        }

        private void CreateShortcut(string targetPath, string shortcutPath)
        {
            // Create a shortcut to the application executable
            var shell = new IWshRuntimeLibrary.WshShell();
            var shortcut = (IWshRuntimeLibrary.IWshShortcut)shell.CreateShortcut(shortcutPath);
            shortcut.TargetPath = targetPath;
            shortcut.Save();
        }
        
        // Functions to load and save auto-start preference in your application's settings
        private bool LoadAutoStartPreference()
        {
            // Load and return the auto-start preference from your settings
            // Example: return Properties.Settings.Default.StartOnSignIn;
        }

        private void SaveAutoStartPreference(bool value)
        {
            // Save the auto-start preference in your settings
            // Example: Properties.Settings.Default.StartOnSignIn = value;
            //          Properties.Settings.Default.Save();
        }
    }
}

**Comment by CHerSun** [comment]
@albertputinjobs Personally, I just add a shortcut to NoSleep to Windows Start menu -> Startup folder. Sometimes its hidden in Start menu (not sure why). Just in case - Startup folder is located at `<your_user_folder>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`. In my case that's `C:\Users\CHerSun\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.

Once you add a shortcut there - NoSleep will start on every reboot and it will appear in Windows Task Manager -> Startup tab where you can enable/disable it, along with other software.

![image](https://github.com/CHerSun/NoSleep/assets/14203878/c9c21686-179f-4ad2-bc3b-10d546f15037) 

I'm more than happy to integrate a pull request into the repo, if any1 is willing to create one. Not sure I'll have time to do that myself any time soon, sorry.

**Comment by CHerSun** [comment]
I've opened issues on a few other things I wanted to do for a long time. Might do a review.

**Comment by CHerSun** [comment]
@albertputinjobs I've added your proposed changes along with my long time wants. I've published that as a new release https://github.com/CHerSun/NoSleep/releases. I'd appreciate if you could check if everything works for you.

P.S.: Had to bump .net framework target version to from 4.0 client profile (very base one, long time outdated) to v4.8. Hopefully this won't create issues for people, but if it will - I'll see if this could be adjusted.
