### ISSUE TITLE
Remember enabled/disabled state

### ISSUE THREAD

**Issue by soredake** [CHerSun/NoSleep#7]
It would be nice if there could be an option to remember enabled/disabled state so it will be restored after restart. Or some command line switch to start NoSleep disabled.

**Comment by CHerSun** [comment]
I've intentionally made that behavior. Idea is that if you start NoSleep - you do want it to prevent the sleeping by default. Adding startup state will add extra mess and will force users to manually check the state, rather then knowing it just works by default. Not sure that's a good behavior really. Let's keep this issue open for a while to see if other ppl want that.

**Comment by CHerSun** [comment]
Thought more about this, decided to add an option to remember the state with the default being the old behavior. Could you check the fresh version from releases (https://github.com/CHerSun/NoSleep/releases/tag/1.3.0)?

![screenshot](https://github.com/user-attachments/assets/dab3a843-ea96-43ee-8990-22437e13841e)

**Comment by CHerSun** [comment]
Closing this issue for now.

In case of any problems please just tag me here or create a new issue.
